# Generated by Django 3.0.4 on 2020-03-22 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='', upload_to='contacts/photo', verbose_name='Фотография')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='Должность')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('working', models.CharField(max_length=170, verbose_name='Режим работы')),
                ('address', models.CharField(max_length=170, verbose_name='Адрес')),
                ('vk_social', models.URLField(blank=True, verbose_name='Ссылка Вконтакте')),
                ('fb_social', models.URLField(blank=True, verbose_name='Ссылка Facebook')),
                ('tw_social', models.URLField(blank=True, verbose_name='Ссылка Twitter')),
                ('inst_social', models.URLField(blank=True, verbose_name='Ссылка Instagram')),
                ('ok_social', models.URLField(blank=True, verbose_name='Ссылка Одноклассники')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
