# Generated by Django 3.0.4 on 2020-03-29 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20200329_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='inst_social',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='tw_social',
        ),
    ]
