# Generated by Django 3.0.4 on 2020-03-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20200329_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='C:\\django\\crankshaft\\media', verbose_name='Фотография'),
        ),
    ]
