# Generated by Django 3.0.4 on 2020-03-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20200329_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='contacts/photo', verbose_name='Фотография'),
        ),
    ]
