# Generated by Django 3.0.4 on 2020-03-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20200330_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Имя'),
        ),
    ]
